files:
- 
  key: wireguard
  template: '{{privateKey}}'
  dest: out/bird/wireguard/private.key
  privateKey: out/bird/wireguard/private.key
  modules:
  - wireguard
- 
  key: wireguard
  template: '{{publicKey}}'
  dest: out/bird/wireguard/public.key
  privateKey: out/bird/wireguard/private.key
  modules:
  - wireguard
- 
  key: dn42
  src: templates/bird.conf.tmpl
  dest: out/bird/bird.conf
  modules:
  - dn42_registry
  - peers
  reloadCmd: '/usr/bin/birdc configure'
- 
  key: dn42
  src: templates/roa.conf.tmpl
  dest: out/bird/roa.conf
  modules:
  - dn42_registry
  reloadCmd: '/usr/bin/birdc configure'
- 
  key: dn42
  src: templates/peers.conf.tmpl
  dest: out/bird/peers/dn42_peers.conf
  modules:
  - peers
  reloadCmd: '/usr/bin/birdc configure'
- 
  key: dn42
  src: templates/peers.sh.tmpl
  dest: out/bird/wireguard/peers.sh
  modules:
  - peers
  reloadCmd: '/etc/bird/wireguard/wireguard.sh restart'