version: '2.1'
services:
  pause:
    image: k8s.gcr.io/pause:3.1
    network_mode: none
    dns:
    - 172.22.169.1
    - 172.22.169.2
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
  util:
    image: alpine
    command: 'mkdir -p /data/bird/peers /data/wireguard'
    volumes:
    - data:/data
  toolbox:
    build: ./toolbox
    restart: always
    depends_on:
    - pause
    network_mode: service:pause
    cap_add:
    - NET_ADMIN
    volumes:
    - data:/data
    - run:/var/run
  bird:
    build: ./bird
    restart: always
    depends_on: 
    - pause
    network_mode: service:pause
    cap_add:
    - NET_ADMIN
    volumes:
    - /etc/bird:/etc/bird:ro
    volumes:
    - data:/data:ro
    - run:/var/run
  netman:
    build: ./netman
    restart: always
    depends_on:
    - pause
    network_mode: service:pause
    pid: host
    privileged: true
    volumes:
    - data:/data:ro
  configman:
    build: ./configman
    restart: always
    volumes:
    - data:/data
    - run:/var/run
    command: 'sh -c "while true; do yarn start; sleep 3000; done"'
  birdwatcher:
    image: k8s.gcr.io/pause:3.1
    # TODO: Build birdwatcher image, link to bird container
volumes:
  data:
  run: