version: '2.1'
services:
  pause:
    image: k8s.gcr.io/pause:3.1
    network_mode: none
    dns:
    - 172.22.169.1
    - 172.22.169.2
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
  toolbox:
    build: ./toolbox
    restart: always
    depends_on:
    - pause
    network_mode: service:pause
    cap_add:
    - NET_ADMIN
  bird:
    build: ./bird
    restart: always
    depends_on: 
    - pause
    network_mode: service:pause
    cap_add:
    - NET_ADMIN
    volumes:
    - /etc/bird:/etc/bird:ro
  netman:
    build: ./netman
    restart: always
    depends_on:
    - pause
    network_mode: service:pause
    pid: host
    privileged: true
    volumes:
    - /etc/bird:/etc/bird:ro
  alicelg:
    image: k8s.gcr.io/pause:3.1
    # TODO: Build alice image